-- Tabela de Doações
create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  descricao text not null,
  categoria text not null,
  quantidade text not null,
  zip text not null,
  address text not null,
  number text not null,
  complement text,
  neighborhood text not null,
  city text not null,
  hours text not null,
  contato_email text not null,
  contato_telefone text not null
);

-- Habilitar RLS (safe to run multiple times)
alter table public.donations enable row level security;

-- Políticas de segurança (drop first to ensure idempotency)
drop policy if exists "Doações são visíveis para todos" on public.donations;
create policy "Doações são visíveis para todos"
on public.donations for select
to public
using (true);

drop policy if exists "Apenas usuários autenticados podem criar doações" on public.donations;
create policy "Apenas usuários autenticados podem criar doações"
on public.donations for insert
to authenticated
with check (true);

drop policy if exists "Apenas usuários autenticados podem deletar doações" on public.donations;
create policy "Apenas usuários autenticados podem deletar doações"
on public.donations for delete
to authenticated
using (true);

drop policy if exists "Apenas usuários autenticados podem atualizar doações" on public.donations;
create policy "Apenas usuários autenticados podem atualizar doações"
on public.donations for update
to authenticated
using (true)
with check (true);
