-- Tabela de Doações
create table public.donations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  descricao text not null,
  categoria text not null,
  quantidade text not null,
  local text not null,
  contato_email text not null,
  contato_telefone text not null
);

-- Habilitar Row Level Security (RLS) para segurança
alter table public.donations enable row level security;

-- Política 1: Todos podem ver as doações (Público)
create policy "Doações são visíveis para todos"
on public.donations for select
to public
using (true);

-- Política 2: Apenas usuários autenticados podem criar doações
create policy "Apenas usuários autenticados podem criar doações"
on public.donations for insert
to authenticated
with check (true);

-- Política 3: Apenas usuários autenticados podem deletar doações
create policy "Apenas usuários autenticados podem deletar doações"
on public.donations for delete
to authenticated
using (true);
