-- Tabela de Serviços
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null,
  address text not null,
  number text,
  complement text,
  neighborhood text not null,
  city text not null,
  zip text not null,
  phone text not null,
  email text not null,
  hours text not null,
  description text not null,
  services_offered text[] not null
);

-- Habilitar RLS
alter table public.services enable row level security;

-- Políticas de segurança
drop policy if exists "Serviços são visíveis para todos" on public.services;
create policy "Serviços são visíveis para todos"
on public.services for select
to public
using (true);

drop policy if exists "Apenas usuários autenticados podem criar serviços" on public.services;
create policy "Apenas usuários autenticados podem criar serviços"
on public.services for insert
to authenticated
with check (true);

drop policy if exists "Apenas usuários autenticados podem deletar serviços" on public.services;
create policy "Apenas usuários autenticados podem deletar serviços"
on public.services for delete
to authenticated
using (true);

drop policy if exists "Apenas usuários autenticados podem atualizar serviços" on public.services;
create policy "Apenas usuários autenticados podem atualizar serviços"
on public.services for update
to authenticated
using (true)
with check (true);
